# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 781, 561))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_label = QtWidgets.QLabel(self.page)
        self.label_label.setGeometry(QtCore.QRect(310, 30, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_label.setFont(font)
        self.label_label.setObjectName("label_label")
        self.textEdit = QtWidgets.QTextEdit(self.page)
        self.textEdit.setGeometry(QtCore.QRect(230, 90, 301, 331))
        self.textEdit.setObjectName("textEdit")
        self.name_label = QtWidgets.QLabel(self.page)
        self.name_label.setGeometry(QtCore.QRect(440, 20, 301, 16))
        self.name_label.setObjectName("name_label")
        self.save_pushButton = QtWidgets.QPushButton(self.page)
        self.save_pushButton.setGeometry(QtCore.QRect(170, 450, 111, 31))
        self.save_pushButton.setObjectName("save_pushButton")
        self.back_pushButton = QtWidgets.QPushButton(self.page)
        self.back_pushButton.setGeometry(QtCore.QRect(460, 450, 91, 31))
        self.back_pushButton.setObjectName("back_pushButton")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.files_comboBox = QtWidgets.QComboBox(self.page_2)
        self.files_comboBox.setGeometry(QtCore.QRect(190, 150, 321, 22))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.files_comboBox.setFont(font)
        self.files_comboBox.setObjectName("files_comboBox")
        self.path_lineEdit = QtWidgets.QLineEdit(self.page_2)
        self.path_lineEdit.setGeometry(QtCore.QRect(180, 70, 341, 20))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.path_lineEdit.setFont(font)
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(170, 40, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(190, 120, 141, 16))
        self.label_2.setObjectName("label_2")
        self.create_pushButton = QtWidgets.QPushButton(self.page_2)
        self.create_pushButton.setGeometry(QtCore.QRect(500, 420, 111, 31))
        self.create_pushButton.setObjectName("create_pushButton")
        self.update_pushButton = QtWidgets.QPushButton(self.page_2)
        self.update_pushButton.setGeometry(QtCore.QRect(120, 250, 91, 31))
        self.update_pushButton.setObjectName("update_pushButton")
        self.delete_pushButton = QtWidgets.QPushButton(self.page_2)
        self.delete_pushButton.setGeometry(QtCore.QRect(300, 250, 91, 31))
        self.delete_pushButton.setObjectName("delete_pushButton")
        self.read_pushButton = QtWidgets.QPushButton(self.page_2)
        self.read_pushButton.setGeometry(QtCore.QRect(470, 250, 91, 31))
        self.read_pushButton.setObjectName("read_pushButton")
        self.status_label = QtWidgets.QLabel(self.page_2)
        self.status_label.setGeometry(QtCore.QRect(120, 350, 391, 21))
        self.status_label.setObjectName("status_label")
        self.lineEdit = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit.setGeometry(QtCore.QRect(470, 380, 191, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(460, 350, 171, 16))
        self.label_3.setObjectName("label_3")
        self.search_pushButton = QtWidgets.QPushButton(self.page_2)
        self.search_pushButton.setGeometry(QtCore.QRect(560, 70, 81, 21))
        self.search_pushButton.setObjectName("search_pushButton")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_label.setText(_translate("MainWindow", "LABEL"))
        self.name_label.setText(_translate("MainWindow", "FILE NAME : "))
        self.save_pushButton.setText(_translate("MainWindow", "SAVE"))
        self.back_pushButton.setText(_translate("MainWindow", "BACK"))
        self.path_lineEdit.setText(_translate("MainWindow", "example"))
        self.label.setText(_translate("MainWindow", "ENTER PATH"))
        self.label_2.setText(_translate("MainWindow", "FILES AVAILABLE"))
        self.create_pushButton.setText(_translate("MainWindow", "CREATE"))
        self.update_pushButton.setText(_translate("MainWindow", "UPDATE"))
        self.delete_pushButton.setText(_translate("MainWindow", "DELETE"))
        self.read_pushButton.setText(_translate("MainWindow", "READ"))
        self.status_label.setText(_translate("MainWindow", "STATUS"))
        self.label_3.setText(_translate("MainWindow", "ENTER FILE NAME"))
        self.search_pushButton.setText(_translate("MainWindow", "SEARCH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

